version: '3'
services:
  db:
    image: postgres:latest
    restart: always
    volumes:
      - data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
  redis:
    image: redis:latest
    restart: always
    env_file:
      - .env
    ports:
      - "6379:6379"
  web_api:
    build: .
    restart: always
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    expose:
      - "8000"
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
#    entrypoint: ''
  celery:
    build: .
    entrypoint: ''
    command: celery -A core worker -l INFO
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - web_api
      - redis
      - db
volumes:
  data: