version: '3'
services:
  db:
    image: postgres:latest
    restart: always
    volumes:
      - data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
  redis:
    image: redis:latest
    restart: always
    env_file:
      - .env
    ports:
      - "6379:6379"
  web_api:
    build: .
    restart: always
    volumes:
      - .:/app
      - static_volume:/staticfiles
      - media_volume:/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
  celery:
    build: .
    entrypoint: ''
    command: celery -A core worker -l INFO
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - db
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/staticfiles
      - media_volume:/media
    depends_on:
      - web_api
volumes:
  data:
  static_volume:
  media_volume: